version: 2.1

orbs:
  architect: giantswarm/architect@5.5.0

workflows:
  test:
    jobs:
      - architect/go-build:
          context: architect
          name: go-test
          binary: app-migration-cli
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
